config/routes.rb
RailsApp::Application.routes.draw do

  # Redirect devise to prevent new users from being created
  devise_for :users
  #, :controllers => { :registrations => "registrations" }

  # Set index
  get "index", to: "main#index"
  root to: "main#index"

  # Namespace resource routes under admin
  namespace :admin do
    root to: "admin#index"
    resources :pictures, :people, :projects
  end

  # Add dynamic routing
  get "/:id", to: "main#project_page"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :project
  attr_accessible :caption, :credit, :weight, :bitmap, :project_id, :active, :href
  base = ENV['OPENSHIFT_DATA_DIR']? ENV['OPENSHIFT_DATA_DIR'] : ':rails_root/'
  has_attached_file :bitmap,
    :url  => '/uploads/:class/:attachment/:id/:style/:basename.:extension',
    :path  => base + 'public:url',
    :styles => {
      :large => ["1280", :jpg],
      :medium => ["640", :jpg],
      :small => ["320", :jpg],
      :thumb => ["160x160#", :jpg]
  }
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::AdminController
  # GET /admin/pictures
  # GET /admin/pictures.json
  def index
    @pictures = Picture.order("id DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /admin/pictures/1
  # GET /admin/pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /admin/pictures/new
  # GET /admin/pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /admin/pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /admin/pictures
  # POST /admin/pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to [:admin, @picture], notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/pictures/1
  # PUT /admin/pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to [:admin, @picture], notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pictures/1
  # DELETE /admin/pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to admin_pictures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/pictures/_form.html.erb
<%= form_for [:admin, @picture] do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.text_field :credit %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.select :project_id, Project.all.collect {|p| [p.title, p.id] } %>
  </div>
  <div class="field">
     <%= f.file_field :bitmap %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active, class: "active" %>
  </div>
  <div class="field">
    <%= f.label :href %><br>
    <%= f.text_field :href %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pictures/_info.html.erb
<h4><%= picture.caption %></h4>
<p>
	<%= picture.credit %>
</p>
<p><%= picture.href %></p>
<p>
	<label>Weight:</label> <%= picture.weight %><br/>
	<label>Active:</label> <%= picture.active %><br/>
	<label>Project:</label> <%= unless picture.project.nil? then picture.project.title end %><br/>
</p>
<%= image_tag picture.bitmap.url %>

app/views/admin/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_picture_path(@picture) %> |
<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/index.html.erb
<h1>Pictures List</h1>

<br>
<%= link_to 'New Picture', new_admin_picture_path, class: "btn btn-large" %>
<br>

<div class="list">
	<% @pictures.each do |picture| %>
	<article>
		<%= render partial: "info", locals: { picture: picture } %>
		<div class="actions">
      <%= link_to 'Show', admin_picture_path(picture), class: "btn" %>
      <%= link_to 'Edit', edit_admin_picture_path(picture), class: "btn" %>
      <%= link_to 'Destroy', admin_picture_path(picture), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
    </div>
	</article>
	<% end %>
</div>

app/views/admin/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/show.html.erb
<article>
  <%= render partial: "info", locals: { picture:@picture } %>
</article>
<%= link_to 'Edit', edit_admin_picture_path(@picture) %> |
<%= link_to 'Back', admin_pictures_path %>