config/routes.rb
RailsApp::Application.routes.draw do

  # Redirect devise to prevent new users from being created
  devise_for :users
  #, :controllers => { :registrations => "registrations" }

  # Set index
  get "index", to: "main#index"
  root to: "main#index"

  # Namespace resource routes under admin
  namespace :admin do
    root to: "admin#index"
    resources :pictures, :people, :projects
  end

  # Add dynamic routing
  get "/:id", to: "main#project_page"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :awards, :client, :company, :credit, :date, :description, :role, :slug, :summary, :title, :website_url, :bitmap, :active

  validates_presence_of :title

  before_create :create_slug

  base = ENV['OPENSHIFT_DATA_DIR']? ENV['OPENSHIFT_DATA_DIR'] : ':rails_root/'
  has_attached_file :bitmap,
    :url  => '/uploads/:class/:attachment/:id/:style/:basename.:extension',
    :path  => base + 'public:url',
    :styles => {
      :small => ["350", :jpg],
      :square => ["350x350#", :jpg]
    }

  def to_param
    slug
  end

  def create_slug
    self.slug = self.title.parameterize
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.order("id DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
    @project = Project.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/new
  # GET /admin/projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /admin/projects/1/edit
  def edit
    @project = Project.find_by_slug(params[:id])
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/projects/1
  # PUT /admin/projects/1.json
  def update
    @project = Project.find_by_slug(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project = Project.find_by_slug(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to admin_projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "title" %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: "summary" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "description" %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client, class: "client" %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.text_field :credit, class: "credit" %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role, class: "role" %>
  </div>
  <div class="field">
    <%= f.label :website_url %><br>
    <%= f.text_field :website_url, class: "url" %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, :start_year => 2001, class: "date" %>
  </div>
  <div class="field">
    <%= f.label :awards %><br>
    <%= f.text_area :awards, class: "awards" %>
  </div>
  <div class="field">
    <%= f.label :bitmap %><br>
    <%= f.file_field :bitmap %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: "slug" %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active, class: "active" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/_info.html.erb
<h2><%= project.title %></h2>
<h4><%= raw project.summary %></h4>
<p><%= raw project.description %></p>
<h5><strong>Client:</strong> <%= project.client %> </h5>
<h5><strong>Credit</strong> <%= project.credit %> </h5>
<h5><strong>Role:</strong> <%= project.role %> </h5>
<h5><strong>Website:</strong> <%= link_to project.website_url %> </h5>
<h5><strong>Date:</strong> <%= project.date %> </h5>
<h5><strong>Awards</strong> <%= project.awards %> </h5>
<h5><strong>Slug:</strong> <%= project.slug %> </h5>
<h5><strong>Active:</strong> <%= project.active %> </h5>
<p><%= image_tag project.bitmap.url %></p>

app/views/admin/projects/edit.html.erb
<h2>Edit project</h2>

<%= render 'form' %>

<%= link_to 'Show', admin_project_path(@project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h2>Project List</h2>

<br>
<%= link_to 'New Project', new_admin_project_path, class: "btn btn-primary" %>
<br>

<div class="list">
	<% @projects.each do |project| %>
	<article>
		<%= render partial: "info", locals: { project: project } %>
		<div class="actions">
			<%= link_to 'Show', admin_project_path(project), class: "btn" %>
			<%= link_to 'Edit', edit_admin_project_path(project), class: "btn" %>
			<%= link_to 'Destroy', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
		</div>
	</article>
	<% end %>
</div>

app/views/admin/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<article>
  <%= render partial: "info", locals: { project: @project } %>
  <%= link_to 'Edit', edit_admin_project_path(@project), class: "btn" %>
  <%= link_to 'Back', admin_projects_path, class: "btn" %>
</article>