config/routes.rb
RailsApp::Application.routes.draw do

  # Redirect devise to prevent new users from being created
  devise_for :users
  #, :controllers => { :registrations => "registrations" }

  # Set index
  get "index", to: "main#index"
  root to: "main#index"

  # Namespace resource routes under admin
  namespace :admin do
    root to: "admin#index"
    resources :pictures, :people, :projects
  end

  # Add dynamic routing
  get "/:id", to: "main#project_page"

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :biography, :email, :name, :resume, :summary, :bitmap
  base = ENV['OPENSHIFT_DATA_DIR']? ENV['OPENSHIFT_DATA_DIR'] : ':rails_root/'
  has_attached_file :bitmap,
    :url  => '/uploads/:class/:attachment/:id/:style/:basename.:extension',
    :path  => base + 'public:url'
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < Admin::AdminController
  # GET /admin/people
  # GET /admin/people.json
  def index
    @people = Person.order("id DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /admin/people/1
  # GET /admin/people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /admin/people/new
  # GET /admin/people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /admin/people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /admin/people
  # POST /admin/people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to [:admin, @person], notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/people/1
  # PUT /admin/people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to [:admin, @person], notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/people/1
  # DELETE /admin/people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to admin_people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/admin/people/_form.html.erb
<%= form_for [:admin, @person] do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_field :resume %>
  </div>
  <div class="field">
    <%= f.label :bitmap %><br>
    <%= f.file_field :bitmap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/people/_info.html.erb
<h2><%= person.name %></h2>
<h4><%= raw person.summary %></h4>
<p><%= raw person.biography %></p>
<a href="mailto:<%= person.email %>"><%= person.email %></a>
<a href="<%= person.resume %>" target="_blank"><%= person.resume %></a>
<p><%= image_tag person.bitmap.url %></p>

app/views/admin/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_person_path(@person) %> |
<%= link_to 'Back', admin_people_path %>

app/views/admin/people/index.html.erb
<h2>People List</h2>

<div class="list">
	<% @people.each do |person| %>
	<article>
		<%= render partial: "info", locals: { person: person } %>
		<div class="actions">
			<%= link_to 'Show', admin_person_path(person), class: "btn" %>
			<%= link_to 'Edit', edit_admin_person_path(person), class: "btn" %>
			<%= link_to 'Destroy', admin_person_path(person), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
		</div>
	</article>
	<% end %>
</div>

<br>

<%= link_to 'New Person', new_admin_person_path, class: "btn btn-primary" %>

app/views/admin/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_people_path %>

app/views/admin/people/show.html.erb
<article>
  <%= render partial: "info", locals: { person: @person } %>
  <%= link_to 'Edit', edit_admin_person_path(@person), class: "btn" %>
  <%= link_to 'Back', admin_people_path, class: "btn" %>
</article>